name: Check for changes

permissions:
  contents: write

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'reset.sh'
      - '.github/workflows/reset.yml'
    branches: [ "main" ]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0

      - name: Check for changes
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          node index

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *
          git commit -am "Update info"
          git push
